name: Codegen

on:
  workflow_call:
    inputs:
      PR_NUMBER:
        required: true
        type: number
    secrets:
      USER_GITHUB_TOKEN:
        required: true
jobs:
  rush-update:
    name: rush update
    timeout-minutes: 15
    runs-on: ubuntu-latest
    steps:
      - name: setup Node
        uses: actions/setup-node@v3
        with:
          node-version: '18.18.0'

      - name: Check out code base
        uses: actions/checkout@v3

      - name: checkout code base
        run: gh pr checkout ${{ inputs.PR_NUMBER }}
        env:
          GH_TOKEN: ${{ secrets.USER_GITHUB_TOKEN }}

      - name: cache rush
        id: cache
        uses: actions/cache@v3.2.2
        with:
          path: common/temp
          key: ${{ runner.os }}-build-branch-${{ hashFiles('common/config/rush/repo-state.json') }}
          restore-keys: |
            ${{ runner.os }}-build-pr-
            ${{ runner.os }}-build-
            ${{ runner.os }}-

      - name: rush update
        run: node common/scripts/install-run-rush.js update

      - name: rush build
        run: node common/scripts/install-run-rush.js build

      - name: push changes
        run: |
          npm install --global lint-staged
          npm install --global prettier
          git config --global user.email "support@github.com"
          git config --global user.name "dependabot[bot]"
          git add .
          git commit -m 'chore(deps): update shrinkwrap'
          git push
        env:
          GH_TOKEN: ${{ secrets.USER_GITHUB_TOKEN }}

